name: release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - run: pip install build twine

    - run: python -m build

    - run: twine check --strict dist/*

    - run: twine upload dist/* --disable-progress-bar
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}